from binance.client import Client


SYMBOL = 'BTCUSDT'
INTERVAL = Client.KLINE_INTERVAL_15MINUTE

RAW_DATASET_START_DATETIME = "1 Jan, 2019"
RAW_DATASET_END_DATETIME = "30 Jul, 2021"

NEW_FILE_NAME_WITHOUT_EXTENSION = '{SYMBOL}_{INTERVAL}_{START}_{END}'.format(
    SYMBOL=SYMBOL,
    INTERVAL=INTERVAL,
    START=RAW_DATASET_START_DATETIME,
    END=RAW_DATASET_END_DATETIME
)

RAW_DATASET_DIRECTORY = 'datasets_raw'
RAW_DATASET_FULL_PATH = '{DIRECTORY}/{FILENAME}.csv'.format(
    DIRECTORY=RAW_DATASET_DIRECTORY,
    FILENAME=NEW_FILE_NAME_WITHOUT_EXTENSION
)
